# <span style="color:red"> QTM 151 - Quiz 3 </span>

## Please submit as an HTML file

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [1]:
# Write your answer here:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [2]:
# Import relevant libraries
import numpy as np 
import pandas as pd


<font size = "5">

(1) Replace values in a column

<font size = "3">

- Load the data from "constructors.csv", assigning it to a DataFrame.
- In the "nationality" column, replace the values "British", "Japanese", and "Irish" with "UK", "Japan", and "Ireland", respectively.
- For full credit, do this by using the ``.replace`` command **one time**

In [ ]:
# Your answer here
# Load dataset constructors.csv
df_constructor = pd.read_csv("data_raw/constructors.csv")

# Replace values in nationality column as specified
df_constructor["nationality"] = df_constructor["nationality"].replace({"British": "UK", "Japanese": "Japan", "Irish": "Ireland"})

display(df_constructor.head())

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,UK,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,UK,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

<font size = "5">

(2) Aggregate and query

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame. Do the following:

- Extract the subset corresponding to 'constructorId == 51' using ```.query()```
- Group by the column "driverId", and then aggregate the maximum over the "laps" column for each driver.
- Extract the subset of drivers with maximum of laps $\ge 20$. Assign this to a DataFrame with a name of your choice.

For full credit, perform all the steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** I only see your final submission, not the code you wrote along the way. It might be easier to break it up into multiple lines, then combine when you're done.

In [4]:
# Your answer here
# Load dataset sprint_results.csv
df_sprint = pd.read_csv("data_raw/sprint_results.csv")

# Extract and compute the dataset df_sprint_51 as specified 
df_sprint_51 = (df_sprint.query("constructorId == 51") # Extract the subset of constructorId 51
                .groupby("driverId") # Group by driverId
                .agg({"laps": "max"}) # Aggregate the maximum over laps
                .loc[lambda x: x["laps"] >= 20]) # Extract the subset with maximum of laps >= 20

display(df_sprint_51)

          laps
driverId
8           24
822         24
841         24
855         24

<font size = "5">

(3) Recode a numeric column

<font size = "3">

- Import data from "races.csv" and assign it to a DataFrame
- Recode the "year" column into a new column "year_brackets"
with the following categories

$\qquad$ ``` ["1950-1965","1966-1980","1981-onwards"] ```

The easiest method is ``pd.cut()`` but you are not required to use this.

In [5]:
# Your answer here
# Load dataset races.csv
df_races = pd.read_csv("data_raw/races.csv")

# Define bins and labels to record year column
bins = [1949, 1965, 1980, 2024]
labels = ["1950-1965", "1966-1980", "1981-onwards"]

# Record year into a year_brackets using pd.cut 
df_races["year_brackets"] = pd.cut(df_races["year"], bins=bins, labels=labels)

display(df_races.head())

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,year_brackets
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards

<font size = "5">

(4) Aggregate and sort

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2)). Do the following:

- Group by "driverId", and then aggregate the average (mean) over the "laps" column.
- Sort the teams by average laps in **descending** order using ``.sort_values()``. Assign this to a DataFrame with a name of your choice.

For full credit, perform both steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** Same hint as problem 2. You can chain commands together later.

In [6]:
# Your answer here
# Previously loaded sprint_results.csv as df_sprint

# Extract and compute the dataset df_sprint_avg as specified 
df_sprint_avg = (df_sprint.
                 groupby("driverId") # group by driverId
                 .agg({"laps": "mean"}) # aggregate the mean over laps
                 .sort_values(by="laps", ascending=False)) # sort by laps in descending order

display(df_sprint_avg.head())

               laps
driverId
825       22.666667
1         21.166667
832       21.166667
854       21.166667
852       21.166667

<font size = "5">

(5) Rename column

<font size = "3">

- Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2))

- Rename the column "time" to "time_unformatted". The names of the other columns should be left intact.

- Print (or display) the DataFrame to ensure the column was renamed correctly.

In [7]:
# Your answer here
# Previously loaded sprint_results.csv as df_sprint

# Rename time column to time_unformatted 
df_sprint = df_sprint.rename(columns={"time": "time_unformatted"})

# Display the DataFrame after renaming
display(df_sprint.head())

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_unformatted,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1

<font size = "5">

(6) Merge dataset

<font size = "3">

- Import the data from "sprint_results.csv" and "constructors.csv", assigning them to two DataFrames (you can also re-use the DataFrames you created above.)

- Create a new dataset with  ``pd.merge()``. Treat "sprint_results.csv" as the primary dataset and "constructors.csv" as the secondary dataset. The merge should be based on the column "constructorId".
- To get full credit **ONLY** merge the "nationality" column from the secondary dataset (not all the columns)
- Print (or display) the resulting merged DataFrame to the screen.

**Hint**: Before you start typing "pd.merge(...)" try printing out the two DataFrames you want to merge, excluding any columns that shouldn't be included.

In [8]:
# Your answer here
# Previously loaded constructors.csv as df_constructor and sprint_results.csv as df_sprint

# Display two datasets to check columns 
# display(df_constructor.head())
# display(df_sprint.head())

# Merge dataset with sprint_results.csv as primary dataset and constructors.csv as secondary dataset (based on "constructorId")
df_merged = df_sprint.merge(df_constructor[["constructorId", "nationality"]], on="constructorId", how="left")

# Display the merged DataFrame
display(df_merged.head())

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_unformatted,milliseconds,fastestLap,fastestLapTime,statusId,nationality
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,Austrian
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,German
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,German
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,Italian
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,UK